version: "3.9"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    env_file: "./.env"
    expose:
      - 3333
      - 4200
    ports:
      - "3333:3333"
      - "4200:4200"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example